name: potato_4cut_v2
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_messaging: ^16.0.3
  dio: ^5.9.0
  flutter_screenutil: ^5.9.3
  go_router: ^16.3.0
  flutter_svg: ^2.2.1
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  camera: ^0.11.3
  flutter_riverpod: ^2.6.1
  sign_in_with_apple: ^6.1.3
  google_sign_in: ^6.2.3
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  path_provider: ^2.1.5
  gal: ^2.3.2
  uuid: ^4.5.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.3.3
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce_generator: 1.10.0
  flutter_lints: ^5.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/config/

  fonts:
    - family: ownglyph_pdh
      fonts:
        - asset: assets/fonts/ownglyph_pdh.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
